odom: /odom
scan: /scan
point_cloud: None
#  topic: /velodyne_points
#  z_range:
#    - 0.3
#    - 0.6

device: cpu

mapper:
  p: 0.5
  X_lim:
    - 0
    - 6.4
  Y_lim:
    - -3.2
    - 3.2
  resolution: 0.1
  size: None
  # Keep this same as above
  device: cpu